const { GoogleGenerativeAI } = require('@google/generative-ai');

if (!process.env.GOOGLE_AI_KEY) {
  console.error('Google AI API key is not set in environment variables');
  process.exit(1);
}

const genAI = new GoogleGenerativeAI(process.env.GOOGLE_AI_KEY);

/**
 * generateScriptFromPlainEnglish(scenario, framework)
 * Takes a plain-English scenario (like "Open the app, log in with user X, 
 * then verify the dashboard") and a framework (XCUITest/Espresso/Playwright),
 * and returns a code snippet generated by the AI.
 */
async function generateScriptFromPlainEnglish(scenario, framework = 'XCUITest') {
  // Here we tailor the prompt to your test framework
  const prompt = `
You are an AI specialized in generating automated test scripts for ${framework}.
The user scenario is:
"${scenario}"

Create a comprehensive ${framework} test script that:
1) Follows best practices.
2) Is well-structured and readable.
3) Includes any assumptions if UI elements are unknown.

Return only the script without extra commentary.
`;

  try {
    const model = genAI.getGenerativeModel({ model: 'gemini-pro' });
    const response = await model.generateContent(prompt);
    return response.response.text();
  } catch (error) {
    console.error('Error generating plain-English script:', error);
    throw error;
  }
}

module.exports = { generateScriptFromPlainEnglish };